# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7k325tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.cache/wt [current_project]
set_property parent.project_path F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/ip_repo/IP_sync_1.0
  f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/library
} [current_project]
update_ip_catalog
set_property ip_output_repo f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/include/parameters.vh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/addr_rand_interl.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/prbm_mem.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/define.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_parameters.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_parameters.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/ldpc_parameters.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_functions.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_addr_gen_tab.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/enc/define.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/enc/ldpc_parameters.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/map_i_band_all.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/map_p_band_all.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/pilot.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/preamb_q_bit.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/preamb_i_bit.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/plc_bit_preambule.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/pream_freq_band_all.svh
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/pream_tsync_band_all.svh
}
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/addr_rand_interl.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/prbm_mem.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/define.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_parameters.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_parameters.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/ldpc_parameters.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_functions.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_addr_gen_tab.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/enc/define.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/enc/ldpc_parameters.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/map_i_band_all.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/map_p_band_all.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/pilot.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/preamb_q_bit.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/preamb_i_bit.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/plc_bit_preambule.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/pream_freq_band_all.svh]
set_property file_type "Verilog Header" [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/input_data/pream_tsync_band_all.svh]
read_verilog -library xil_defaultlib -sv {
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/DeFEC.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/FEC.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/LLR_mux.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/P2S_conv_4x1.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/P2S_conv_8x1.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/RX_phy.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/S2P_conv_1x4.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/S2P_conv_1x8.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/TX_phy.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/add_cp.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/xcorr/calculate_mean.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/codec_buffer_nD_slogic.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/codec_mem_block.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/coder_CRC.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/control.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/control_index_symb.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/count_err.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/xcorr/count_sop_dtct.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/xcorr/data_upsampler.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/deInterleaver.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decoder_CRC.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/deinterl_ram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/demapper_ss.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/demappersv.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/descrambler.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/equalizer.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/fftshift.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/xcorr/filter_sop.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/xcorr/find_max.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/freq_correct/fr_sync.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/ifft.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/interl_addr_rom.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/interl_ram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/interlayer_rmcp.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/interleaver.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_addr_gen.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_cnode.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_cnode_engine.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_ctrl.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_engine.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_engine_sink.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_ibuffer.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_ibuffer_dwc.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_mem.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_source.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_vnode.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/decodeLDPC/ldpc_dec_vnode_engine.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/enc/ldpc_enc.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/enc/ldpc_enc_addr_gen.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/soft_demod/llr_even_qam_demapper.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/soft_demod/llr_even_qam_demapper_core.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/map_i_ram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/map_p_ram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/mapper.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/modulator.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/xcorr/my_bram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/pack_finder.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/parallel2series.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/DeFEC/parallel2series_FIFO.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/freq_correct/prb_fsync_ram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/xcorr/prb_tsync_ram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/prbs/prbs23_check.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/prbs/prbs23_gen.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/modulators/qam16_mod.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/modulators/qam64_mod.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/modulators/qpsk_mod.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/xcorr/ram.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/scramb_subcarier.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/EDM/FEC/scrambler.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/series2parallel.sv
  {F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/submodule equalizer/sub_eq_1.sv}
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/freq_correct/sync_fifo.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Tx/transport_block_shaper.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/xcorr/xcorr_fft_sub.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/xcorr/xcorr_ifft_sub.sv
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/Rx/xcorr/xcorr_main_lite.sv
}
read_verilog -library xil_defaultlib {
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/imports/Single_mod/ibuf.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/imports/Single_mod/FPGA_reset.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/imports/Single_mod/RAshift16_4_up.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/imports/Single_mod/on_off_wire.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/imports/Single_mod/Decoder_SPI_2.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/imports/modules/pulse_expander.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/modem_axi_lite.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/only_rx.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/only_tx.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/speed_test.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/switch.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/modem.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/axis_async_fifo.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/axis_cobs_decode.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/axis_cobs_encode.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/axis_fifo.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/axis_gmii_rx.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/axis_gmii_tx.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/lfsr.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/FPGA/gmii_files/eth_pump.v
  F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_data_fifo_4/axis_data_fifo_4.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_data_fifo_fhy_defec/axis_data_fifo_fhy_defec.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/div_gen_0/div_gen_0.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/xfft_time_freq/xfft_time_freq.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_data_fifo_ifft/axis_data_fifo_ifft.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/cordic_0/cordic_0.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/div_gen_fr_corr/div_gen_fr_corr.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/cordic_2/cordic_2.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_fifo_downsamp/axis_fifo_downsamp.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/ifft_corr_1_1/ifft_corr_1.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_data_fifo_ifft_corr/axis_data_fifo_ifft_corr.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/fft_corr_1/fft_corr_1.xci

read_ip -quiet F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_data_fifo_0_1/axis_data_fifo_0.xci

add_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_AXI_C2C_0/design_1_AXI_C2C_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_AXI_C2C_0/design_1_AXI_C2C_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_AXI_DMA_0/design_1_AXI_DMA_0_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_CLK_COMMON_0/design_1_CLK_COMMON_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_CLK_COMMON_0/design_1_CLK_COMMON_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_CLK_COMMON_0/design_1_CLK_COMMON_0_late.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_CLK_COMMON_0/design_1_CLK_COMMON_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_AXI_reset_0/design_1_AXI_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_AXI_reset_0/design_1_AXI_reset_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_adc_fifo_ad9364_0_0/util_wfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_dac_fifo_ad9364_0_0/util_rfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_divclk_64_rst1_0/design_1_divclk_64_rst1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_divclk_64_rst1_0/design_1_divclk_64_rst1_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9364_0/design_1_axi_ad9364_0_pps_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9364_0/axi_ad9361_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_adc_fifo_ad9361_1_0/util_wfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_dac_fifo_ad9361_1_0/util_rfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9361_1_0/design_1_axi_ad9361_1_0_pps_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9361_1_0/axi_ad9361_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_adc_fifo_ad9361_2_0/util_wfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_dac_fifo_ad9361_2_0/util_rfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9361_2_0/design_1_axi_ad9361_2_0_pps_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9361_2_0/axi_ad9361_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_adc_fifo_ad9361_3_0/util_wfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_dac_fifo_ad9361_3_0/util_rfifo_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9361_3_0/design_1_axi_ad9361_3_0_pps_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ad9361_3_0/axi_ad9361_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_clk_DSP_0/design_1_clk_DSP_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_clk_DSP_0/design_1_clk_DSP_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_clk_DSP_0/design_1_clk_DSP_0_late.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_clk_DSP_0/design_1_clk_DSP_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_DATA_rst_0/design_1_DATA_rst_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_DATA_rst_0/design_1_DATA_rst_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_spi_0/design_1_axi_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_spi_0/design_1_axi_spi_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_spi_0/design_1_axi_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_spi_0/design_1_axi_spi_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_util_clkdiv_0_0/util_clkdiv_constr.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_modem_0_0/design_1_modem_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/constrs_1/imports/Files_XDC/DSP_Kintex_PM.xdc
set_property used_in_implementation false [get_files F:/work/Izhevsk_project_2_2_eth/Izhevsk_project_2_2_eth/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/constrs_1/imports/Files_XDC/DSP_Kintex_PM.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7k325tffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
